theme: jekyll-theme-cayman

# Site wide configuration

title: accessible research
locale: en_US
logo: # filename of a logo image that has been placed into your images directory
topnav: example_menu
menubar: example_menu
fixed_navbar: example_menu
