theme: jekyll-theme-cayman

# Site wide configuration

title: accessible research
locale: en_US

# --- List of links in the navigation bar --- #
navbar-links:
  Events: "https://accessibleresearch.github.io/events"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
  
  
logo: # filename of a logo image that has been placed into your images directory
topnav: navigation
menubar: <a href="https://accessibleresearch.github.io" class="btn">Home</a>
         <a href="https://accessibleresearch.github.io/events" class="btn">Events</a>
         <a href="https://accessibleresearch.github.io/members" class="btn">Members</a>
fixed_navbar: top
